services:
  mongo:
    image: mongo:7
    container_name: lesson13
    restart: unless-stopped
    ports:
      - "27021:27017"
    volumes:
      - lesson14_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: lesson13

volumes:
  lesson14_mongo_data: